name: GoldEconomy
version: '1.0-SNAPSHOT'
main: com.j43hyun9.goldeconomy1.Main
api-version: '1.20'
softdepend: [Vault]
authors: [J43hyun9]
description: This is Enonomy Plugin
website: https://github.com/j43hyun9/GoldEconomy.git
commands:
  돈:
    aliases: [money,ㄷ,]
    usage: : "/돈"
permissions:
  goldeco.admin: op
  goldeco.use: false
